/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiY1A0TElnOEIrcHVHM2lBVVZ2b01ueTI1Tll2TEVES0tBMFkrSnJJTTVGcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK1VaY2xuQmJkOFdsNGdTOEViRHUvcDZJYUw1L0RQTzdCR0lma1lMWncyZz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIyRkd4OW1YMUEzdkpZZW9LUitXTCtublBOTGh5WnhtZE1NK3o4NWVjREU4PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0RFNNWGd5UGtzRXJsd21tSFA2UWVpR1FyUHd5MWg5OUlUc3RHZndaSzFvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklBUERWNXFnMDZJdzZlNXBQOTJ5bmJCbjEvZ2k1L1h2cW5rc1RPN2tYR1U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImNtSndpa0Zack56UzdhRXB1UE9VcDNUY1IxQWI5Z0pjMkN5cVBxOUI1VzQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNElqTnpZclYvOHR0VXFuQWpuc1hGM25pdTIvdW9aNFk3WVJpRW9QSDEyVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlBRVmFOWCswUUxsYjlmaXlRYnF0K0tqZ3JLNjhqVkZ0ZnJmU3VvYmN4ST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZCZW5xSVJMME9BeDJhYUR6LzR0ZzhRQjZ2dXZFblk3VWVtU3FvTlNIN0YzeW9CYWZ5OGxBeHNnaldBK0lMS3pOUFd6UE1ZYTdMbFRycVhBSEV5MWpRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTA3LCJhZHZTZWNyZXRLZXkiOiJxOThjOHZpczdyYWJOSm9STVRCYmlWYlNWUngvL29MTUk3T3JmdGF2TC9ZPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiI5SmVfYzlQZVJtLWtYMG9DRkttVXhBIiwicGhvbmVJZCI6IjJkMGUzZDg5LTI2YzYtNGQ5Yi05MTE5LWY4YjdhMjIzZDAwYSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJEMkN1T0VSTXNIcG41NjRLVWtqQk1zZnRBUTQ9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaTlFVWVIUWV3b05IOW5uU3ZIQXNtc2lUV3dFPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6Ijc4TDFSUVBNIiwibWUiOnsiaWQiOiIyMzQ4MTA0NDAwMDY2Ojc5QHMud2hhdHNhcHAubmV0In0sImFjY291bnQiOnsiZGV0YWlscyI6IkNPR3Q4b1lCRUl5bTVMa0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJhRi9TWWRvelBvRkkyOUs5YXFoS0doNEVWVFRndW5nNm9LaTh5T2xRb0ZjPSIsImFjY291bnRTaWduYXR1cmUiOiJlKzkvZnZmYmFyS2VBUlhKbzVsYlRLb3UrL0UzNUQ2SEJyVkhwWDI2M3R0aUFodDRmTW5Rb0VGdW9EMk1HK2dRRjRkbnRDaVU5eS9aV1lMZDJ3VlhBUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoicFRmK3pua0x3UmVPYW55Y3VzMFQzTk9URXdmME92V1lwa2RZT1VFNUdROWhVOVJDQ2JmeU05S0d4M2N2czh5Y3BaRUdmZWloZDNZWXhmRnRwTlRHaUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ4MTA0NDAwMDY2Ojc5QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQldoZjBtSGFNejZCU052U3ZXcW9TaG9lQkZVMDRMcDRPcUNvdk1qcFVLQlgifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE3OTM2OTEsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRXlVIn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "234";
const author = process.env.STICKER_AUTHOR || 'Josh';
const packname = process.env.PACKNAME || 'Josh';
const dev = process.env.DEV || '2348104400066';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'Joshtech';
const mode = process.env.MODE || 'private';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
